<?php 
$msg = '"ok"';
if(isset($_REQUEST["data"])){
	$url = 'https://api.hablame.co/sms/envio/';
	/*
	{
		phones:[]
		message:""
	}
	*/
	$a = json_decode($_REQUEST["data"], true);
	foreach($a["phones"] as $d){
		$data = array(
			'cliente' => 10011143, //Numero de cliente
			'api' => 'xCvCzxbtbfjDCAHJumDzt2mUuP6eB8', //Clave API suministrada
			'numero' => $d, //numero o numeros telefonicos a enviar el SMS (separados por una coma ,)
			'sms' => $a["message"], //Mensaje de texto a enviar
			//'fecha' => '2017-10-22 12:00:00', //(campo opcional) Fecha de envio, si se envia vacio se envia inmediatamente (Ejemplo: 2017-12-31 23:59:59)
			'referencia' => 'Bluehack', //(campo opcional) Numero de referencio ó nombre de campaña
		);

		$options = array(
			'http' => array(
				'header'  => "Content-type: application/x-www-form-urlencoded\r\n",
				'method'  => 'POST',
				'content' => http_build_query($data)
			)
		);
		$context  = stream_context_create($options);
		$result1 = file_get_contents($url, false, $context);
		$result = json_decode($result1, true);
		$msg = $result1;

	}
	print '{"st":'.$msg.'}';
}

if(isset($_REQUEST["chk"])){
	// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
	$ch = curl_init();

	curl_setopt($ch, CURLOPT_URL, "https://gateway.watsonplatform.net/assistant/api/v1/workspaces/6bd4fa2c-b931-48d3-b628-24c9bed1ecf2/message?version=2018-07-10");
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch, CURLOPT_POSTFIELDS, "{\"input\": {\"text\": \"".$_REQUEST["chk"]."\"}}");
	curl_setopt($ch, CURLOPT_POST, 1);
	curl_setopt($ch, CURLOPT_USERPWD, "031e2c77-121f-4b1b-8705-982412560501" . ":" . "sERdlnLigJBu");

	$headers = array();
	$headers[] = "Content-Type: application/json";
	curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
	$c = curl_exec($ch);
	$result = json_decode($c, true);
	if (curl_errno($ch)) {
		echo 'Error:' . curl_error($ch);
	}

	foreach($result["intents"] as $i){
		if(($i["intent"] == "ObtenerFotos" || 
			$i["intent"] == "TieneNecesidadEconomica" ||
			$i["intent"] == "Emigrar" || 
			$i["intent"] == "FacilitadorDocumental" )  && $i["confidence"] > 0.7){
			$msg = '"Posible reclutamiento"';
			$ch2 = curl_init();

			curl_setopt($ch2, CURLOPT_URL,"http://hack-api.labs.ml/api/alerts");
			curl_setopt($ch2, CURLOPT_POST, 1);
			$lat="4.".rand(564333, 762542);
			$long="-74.".rand(26328, 201098);
			curl_setopt($ch2, CURLOPT_POSTFIELDS,
						"latitude=".$lat."&longitude=".$long."&typeAlert=6");

			// In real life you should use something like:
			// curl_setopt($ch, CURLOPT_POSTFIELDS, 
			//          http_build_query(array('postvar1' => 'value1')));

			// Receive server response ...
			curl_setopt($ch2, CURLOPT_RETURNTRANSFER, true);

			$server_output = curl_exec($ch2);
			//print $server_output;
 
			curl_close ($ch2);
			
		}
	}
	//$msg=$result;
	print '{"st":'.$msg.', "data":'.$c.'}';
	curl_close ($ch);
}